import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import isothing from '../public/isothing.png'

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>  
        <title>Andras Talas</title>
        <meta name="portfolio" content="Generated by create next app" />
      </Head>
      <main className='bg-white'>
      <div className={styles.pagesec1}>
        <div id="sidebar" className={styles.pagesec11}>
          <div>
            <div className={styles.sidebar}>
              <div className={styles.social}>
                <a  rel="noreferrer"href="https://github.com/ariaxhera" target={'_blank'} className={styles.git}>Github</a>
                <a  rel="noreferrer" target={'_blank'}  href="https://docs.google.com/document/u/4/d/e/2PACX-1vQVz6oKwYtteRJEbheJZ0DpDeHHfFbCSoMexglcKgycxUf7NhEV4J8AxtsHZtBo3AJO7CwVrSpv8KEJ/pub" className={styles.con}>Contact</a>
                <br></br>
                <h2 className={styles.projectit}>Projects</h2>
          
              </div>
              <div className={styles.project}>
                {/* <div className={styles.project1}> */}
                  {/* <div className={styles.posaka} /> */}
                  {/* <h3 className={styles.posakat}>osaka</h3> */}
                {/* </div> */}
                <div className={styles.project2}>
                  <div className={styles.ptype} />
                  <a rel="noreferrer" href='https://wondrous-sawine-3159bb.netlify.app' target={'_blank'} className={styles.ptypet}>typewriter</a>
                </div>
              </div>
              <div className={styles.mwrap}>
              <div id="extension" className={styles.ext}>
              </div>
              <p className={styles.marg2}>15
                16
                17
                18
                19
                20
                21
                22
                23
                24
                25
                26
                27
                28
                29
                30
                31
                32
                33
                34
                35
                36
                37
                38
                39
                40
                41
                42
                43
                44
            </p>
            <p className={styles.marg1}>
              1
              2
              3
              4
              5
              6
              7
              8
              9
              10
              11
              12
              13
              14
              15
              16
              17
              18
              19
              20</p>    
              <p className={styles.marg3}>1
                2
                3
                4
                5
                6
                7 
                8
                9
                10
                11
                12
                13
                14
                15
                16
                17
                18
                19
                20
                21
                22
                23
                24
                25
                26
                27
                28
                29
                30
                31
                32
                33
                34
                35
                36
                37
                38
                39
                40
                41
                42
                43
                44
                45
                46
                47
                48
                49
                50
                51
                52
                53
                54
                55
                56
                57
                58
                59
                60
                61
                62
                </p>
            </div>
            </div> 
          </div>
          </div>
          <div className={styles.pagesec2}>
          <div className={styles.pagesec22}>
            <div id="header" className=''>
              <div id="title">
              <h1 className={styles.title}>Andras Talas</h1>
              </div>
                <div id="subtitle" className={styles.subtitle}>
                <h2 className={styles.subtitle1}>
                Frontend developer/ UX/UI Designer/ Artist</h2>
                <h2 className={styles.subtitle2}>(fuelled by coffee & vanilla tea)</h2>
                </div>
              </div>
            </div>
        <div id="sections">
          <div id="about" className={styles.aboutme}>
            <div>
              <h2 className={styles.aboutit}>About me</h2>
              <p className={styles.aboutp}>
              I am an aesthetics focused Artist with a background
              of illustration, graphic design and a fresh blend of coffee.
              I am currently situated in Sweden where my spark for frontend
              design started, causing a domino effect of finding new knowledge and interests
              for multiple mediums of Design. To briefly name a few: UX/UI Design; Illustration; 3D Art; Frontend Development & Video Editing.
              I have a student learner mindset, I love learning, it keeps me
              grounded, focused and forever developing my craft. </p>
            </div>
          </div>
          <div id="imagecurrent" className={styles.icwrap}>
            <div id="fut" className={styles.current}>
            <h1 className={styles.currentit}>Currently working on</h1>
            <p className={styles.currentep}>
              A website inspired by retro style
              prints talking about the
              history of Osaka up until present day. 
              I am taking up this personal project as the Japanese Graphic designers that I have followed and learnt from
              are a huge inspiration for my choices of colorwork and level of visual prettiness I
              want to acheive.
              <br></br><br></br>A visually aesthetic focused render in a 3D environment,
              heavily inspired by Chen Jiacheng & Sakura Rabbiter, both incredibly talented Game developers.
              I chose this project for I love the 
              flexibility and complexity of 3D renders. It would greatly expand my artistic knowledge and help aid my visual language.
            </p>
              </div>
              <div className={styles.img}>
            <Image src={isothing}  objectFit='contain' />
              </div>
          </div>
          <div id='future' className={styles.future}>
            <h1 className={styles.futuretit}>Future Projects</h1>
            <ul className={styles.futureli}>
              <li>Dark mode for this portfolio page.</li>
              <li>Visual renders in blender and/or Unreal Engine.</li>
              <li>Gallery website for visual side projects.</li>
            </ul>
          </div>
          <div id='skills' className={styles.skills}>
            <h1 className={styles.skillstit}>Skills</h1>
            <ul className={styles.skillsli}>
              <li>Photoshop ~ 5 years</li>
              <li>Figma ~ 2 year</li>
              <li>Blender ~ 1 year</li>
              <li>HTML</li>
              <li>CSS</li>
              <li>Javascript</li>
              <li>Next.js</li>
              <li>Git</li>
            </ul>
          </div>
        </div>
            <div id="color scheme">
            <div className={styles.colorscheme}>
                <div className={styles.cwrap}>
                  <div className={styles.colorschemecube1} />
                  <h3 className={styles.c1t}>
                    <span className={styles.smoky}>Smoky Black</span>
                    <span className={styles.hexsmok}>#100C08</span>
                  </h3>
                  </div>
                <div className={styles.cc1w}>
                  <div className={styles.colorschemecube2} />
                  <h3 className={styles.c2t}>
                    <span className={styles.chest}>Black chestnut oak (kurotsurubami)</span>
                    <span className={styles.hexoak}>#252321</span>
                  </h3>
                </div>
                <div className={styles.cc2w}>
                  <div className={styles.colorschemecube3} />
                  <h3 className={styles.c3t}>
                    <span className={styles.apricot}>Apricot</span>
                    <span className={styles.hexcot}>#FBCEB1</span>
                  </h3>
                </div>
                <div className={styles.cc3w}>
                  <div className={styles.colorschemecube4} />
                  <h3 className={styles.c4t}>
                    <span className={styles.champagne}>Champagne</span>
                    <span className={styles.hexpagne}>#F7E7CE</span>
                  </h3>
                </div>
                <div className={styles.cc4w}>
                  <div className={styles.colorschemecube5} />
                  <h3 className={styles.c5t}>
                    <span className={styles.osakagold}>Osaka Gold</span>
                    <span className={styles.hexosaka}>#BC9365</span>
                  </h3>
                </div>
              </div> 
            </div>
            <div id="case study" className={styles.caseconta}>
              <div className={styles.case}>
                <h1 className={styles.casetit}>Case Study</h1>
                <h2 className={styles.casetit2}>(for those interested)</h2>
              </div>
              <p className={styles.casecont}>Every designer experiences
               the difficult chapter in their journey when they decide
               they need a portfolio website. Countless days, weeks, months designing
               and prototyping different ideas for the UX & UI experience just to be left feeling incomplete or as if
               you have lost sight of the visual goal of your portfolio. I
               spent some time in this period of doubt and revised ideas constantly,
               often thinking I am not doing myself justice.<br></br><br></br>Until I lost motivation in
               the project completely. However, a few days later I decided to let my
               creative self be let free on a tabloid sized page in Figma. Giving myself the oppertunity
               to do anything that spoke to me visually led to me seeing the end goal once
               again, creating a new and much more purposeful inital design. 
               It didn’t just appear out of nowhere however. This webpage may look
               like a notebook planner or a printed poster at times and the reason
               for that is because a large chunk of that newfound motivation came 
               from graphic designers that focused on print. <a className={styles.atli} rel="noreferrer" href='https://www.instagram.com/atelier_gray/' target={'_blank'}>atlier_grey</a> being the 
               most influential of these as they led me through a long journey of 
               discovering other graphic designers that visually spoke to me.</p>
            </div>
          </div>
        </div>
      </main>
      <footer>
        <h4 className={styles.footer}>made with next.js</h4>
      </footer>
    </div>
  )
}
